### ISSUE TITLE
Not good results

### ISSUE THREAD

**Issue by caikw0602** [Stick-To/CenterNet-tensorflow#11]
作者你好。我采用VOC2007训练了centernet模型，batchsize=3，epoch=20，此时的loss已经稳定在5左右，继续训练下去loss不会降低。然而，我采用其他图片进行测试，效果很差，请问是不是我的测试方法有问题或者有什么好的解决办法呢？谢谢！代码和结果如下：

`centernet = net.CenterNet(config, trainset_provider)
centernet.load_weight('./centernet/test-50100')
centernet.load_pretrained_weight('./centernet/test-50100')

img = io.imread('./img/person1.jpg')
img = transform.resize(img, [384,384])
img = np.expand_dims(img, 0)
result = centernet.test_one_image(img)
id_to_clasname = {k:v for (v,k) in classname_to_ids.items()}
scores = result[0]
bbox = result[1]
class_id = result[2]
print(scores, bbox, class_id)
plt.figure(1)
plt.imshow(np.squeeze(img))
axis = plt.gca()
for i in range(len(scores)):
    rect = patches.Rectangle((bbox[i][1],bbox[i][0]), bbox[i][3]-bbox[i][1],bbox[i][2]-bbox[i][0],linewidth=2,edgecolor='b',facecolor='none')
    axis.add_patch(rect)
    plt.text(bbox[i][1],bbox[i][0], id_to_clasname[class_id[i]]+str(' ')+str(scores[i]), color='red', fontsize=12)
plt.show()`

![选区_026](https://user-images.githubusercontent.com/45365909/61560810-363e9280-aa65-11e9-9672-36523997b85c.png)

**Comment by Stick-To** [comment]
batchsize=3，epoch=20 不合适吧， batchsize大一点， epoch多一点， 置信度一般要0.5以上， 损失不动可以降低学习率

**Comment by Stick-To** [comment]
centernet.load_pretrained_weight('./centernet/test-50100')
这一行删掉

**Comment by Stick-To** [comment]
centernet.load_pretrained_weight('./centernet/test-50100)
这一行 是加载预训练模型， 不是加载模型， 
centernet.load_weight('./centernet/test-50100')
 就够了

**Comment by caikw0602** [comment]
感谢你的回复。我的gpu显存是3G，batchsize再大的话就溢出了，loss到5左右了还不可以吗？还应该更低？置信度是指'score_threshold'参数吧？默认是0.1？抱歉，我还没看程序，想先运行起来出个结果。谢谢
