### ISSUE TITLE
What is the mean of "pad_truth_to" please?

### ISSUE THREAD

**Issue by caikw0602** [Stick-To/CenterNet-tensorflow#12]
作者你好，请问“pad_truth_to"这个参数是做什么的呢？这个参数不能小于一张图片中标记的目标数量，是吗？如果不用会影响什么呢？

多谢

**Comment by Stick-To** [comment]
一个batch有多张图， 每张图内目标数量不一样， 要把目标数量pad成相同数目， 否则无法一个batch传入

**Comment by caikw0602** [comment]
多谢回复，一般这个取值参考是多少呢？太大会怎样？

**Comment by caikw0602** [comment]
我用VOC2007数据可以训练，但是用自己的数据就不行了，总是出现pad不能为负的error，我怀疑是这个参数的问题。因为我的数据的目标数量要比VOC的多。

**Comment by Stick-To** [comment]
太大浪费显存， 数据集内框数最多的一张图里的框数加一就好， 大点没关系， 不能小了
