### ISSUE TITLE
I didn't understand this line, could you help me? If the shape of the ground_truth was [-1, 5], the operation of "tf.argmin(ground_truth, axis=0)[0]" got the minimum of y？

### ISSUE THREAD

**Issue by YangYangGirl** [Stick-To/CenterNet-tensorflow#15]
https://github.com/Stick-To/CenterNet-tensorflow/blob/01b31889766bbee563b141ea28bedc2accde151a/CenterNet.py#L189

**Comment by Stick-To** [comment]
because the number of bbox in different images are different
so I padding them with [-1 -1 -1 -1 -1], to input them as a batch

**Comment by Stick-To** [comment]
tf.argmin(ground_truth, axis=0)[0] got the real ground_truth for every image,
by deleting the [-1 -1 -1 -1 -1]
