### ISSUE TITLE
when executing under ubuntu import error

### ISSUE THREAD

**Issue by keithyh** [Stick-To/CenterNet-tensorflow#16]
On ubuntu 16.04, import utils.tfrecord_voc_utils as voc_utils

ModuleNotFoundError: No module named 'utils'

however,this error does not occur on windows10

**Comment by Stick-To** [comment]
set source root dir

**Comment by keithyh** [comment]
under ubuntu ,I still got this error
InvalidArgumentError: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[node IteratorGetNext (defined at /home/skj/tianchibu/CenterNet.py:63) ]]
	 [[node IteratorGetNext (defined at /home/skj/tianchibu/CenterNet.py:63) ]]

**Comment by keithyh** [comment]
runfile('/home/skj/tianchibu/main2.py', wdir='/home/skj/tianchibu')
Reloaded modules: CenterNet
WARNING:tensorflow:From /home/skj/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/skj/tianchibu/CenterNet.py:343: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From /home/skj/tianchibu/CenterNet.py:332: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /home/skj/tianchibu/CenterNet.py:412: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.max_pooling2d instead.
WARNING:tensorflow:From /home/skj/tianchibu/CenterNet.py:422: average_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.average_pooling2d instead.
WARNING:tensorflow:From /home/skj/tianchibu/CenterNet.py:358: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d_transpose instead.
------------------------- epoch 0 -------------------------
reduce lr, lr= 0.0001 now
Traceback (most recent call last):

  File "<ipython-input-8-5c5599582bed>", line 1, in <module>
    runfile('/home/skj/tianchibu/main2.py', wdir='/home/skj/tianchibu')

  File "/home/skj/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/skj/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/skj/tianchibu/main2.py", line 83, in <module>
    mean_loss = centernet.train_one_epoch(lr)

  File "/home/skj/tianchibu/CenterNet.py", line 295, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})

  File "/home/skj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)

  File "/home/skj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)

  File "/home/skj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)

  File "/home/skj/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Need minval < maxval, got 0 >= -208
	 [[{{node random_uniform_1}}]]
	 [[node IteratorGetNext (defined at /home/skj/tianchibu/CenterNet.py:63) ]]
	 [[node IteratorGetNext (defined at /home/skj/tianchibu/CenterNet.py:63) ]]

**Comment by Stick-To** [comment]
May your dataset is your own dataset, you could try voc, may your dataset has some problems
