### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by Tonto5000** [Stick-To/CenterNet-tensorflow#17]
How do you use pretrained weights?
I always get an error stating that backone can‘t be found in the vgg 16

Could anyone provide trained weights?

**Comment by Stick-To** [comment]
the backone of centernet is not vgg16, 
vff16.ckpt is for ssd, refindet, etc.

**Comment by Tonto5000** [comment]
Ok that‘s the hint I took from https://github.com/Stick-To/Object-Detection-API-Tensorflow/blob/master/README.md

So are there any pre trained weights for centernet?
Or would you mind sharing yours?

**Comment by Stick-To** [comment]
Sorry, my pretrained weight was deleted
I can't provide it.

**Comment by Tonto5000** [comment]
But can you say something about the Performance?
Was it better than ssd or yolo?
Or are the results just better when using centernet with pytorch?

**Comment by Stick-To** [comment]
No.
If you want to get great preformance as official, you could use official pytorch code.
my code is just easy to understand
