### ISSUE TITLE
442368 =384*384*3   Invalid argument: Input to reshape is a tensor with 442368 values,

### ISSUE THREAD

**Issue by ZCCDL** [Stick-To/CenterNet-tensorflow#19]
Hello, thank you for replicating so many networks. It's really a great job. This problem occurred when I ran the program. I don't know what went wrong.

Traceback (most recent call last):
  File "test.py", line 74, in <module>
    mean_loss = centernet.train_one_epoch(lr)
  File "/home/training/zcc/CenterNet-tensorflow-master/CenterNet.py", line 298, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "/home/training/anaconda2/envs/zcc/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
。。。
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 442368 values, but the requested shape has 0
         [[{{node Reshape_2}}]]
         [[IteratorGetNext]]
         [[center_detector/cond_5/SparseToDense/_115]]
  (1) Invalid argument: Input to reshape is a tensor with 442368 values, but the requested shape has 0
         [[{{node Reshape_2}}]]
         [[IteratorGetNext]]

**Comment by Stick-To** [comment]
python2.7？   my code is based on python3.7

**Comment by ZCCDL** [comment]
now based on Python 3.7.4 ,got the same issue

**Comment by Stick-To** [comment]
maybe your dataset have some problem, you could try voc dataset
