### ISSUE TITLE
what backbone is used?

### ISSUE THREAD

**Issue by yuskey** [Stick-To/CenterNet-tensorflow#4]
Hey, curious as to what backbone network you used for the data and how easy it is to replace it with something else?

**Comment by Stick-To** [comment]
I use dla34, change variable_scope('backone') and variable_scope('upsampling')

**Comment by yuskey** [comment]
I have a different backbone I want to try with this network, would you be willing to help me out?

**Comment by Stick-To** [comment]
if you have some problems, describe it in issues
