### ISSUE TITLE
OutOfRangeError (see above for traceback): End of sequence 	 [[node IteratorGetNext (defined at G:\git\CenterNet-tensorflow\CenterNet.py:63) ]]

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [Stick-To/CenterNet-tensorflow#7]
I met this issue when training on my own dataset. I realize that my " .tfrecord" file has size = 0 bytes on disk. I think that's the reason why my error occurred. Does anyone have the same issue, and how to fix it? Many thanks!!!!!

**Comment by Stick-To** [comment]
tfrecord generate failed

**Comment by nguyenhoangthuan99** [comment]
thanks!!! I fixed my bug.
