### ISSUE TITLE
Pose estimation

### ISSUE THREAD

**Issue by rafikg** [Stick-To/CenterNet-tensorflow#9]
Did you handle the pose estimation in this repo ?

**Comment by Stick-To** [comment]
didn't, only object detection

**Comment by rafikg** [comment]
@Stick-To Hi, I don't see that you have used the Deformable convolution (DCN) in your DLA ?

**Comment by Stick-To** [comment]
Yes




| |
lixinruworld
|
|
邮箱：lixinruworld@163.com
|

Signature is customized by Netease Mail Master

On 07/13/2019 22:54, R.G wrote:

@Stick-To Hi, I don't see that you have used the Deformable convolution (DCN) in your DLA ?
